<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'nombre',
        'especie_id',
        'recinto_id',
        'cuidador_id',
        'fecha_nacimiento',
        'genero',
        'peso',
    ];

    public function animalcuidadors()
    {
        return $this->hasMany('App\Models\AnimalCuidador','animal_id');
    }

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie','especie_id');
    }

    public function animalrecintos()
    {
        return $this->hasMany('App\Models\AnimalRecinto', 'animal_id');
    }

    public function actividadanimals()
    {
        return $this->hasMany('App\Models\ActividadAnimal','animal_id');
    }
}
